FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 
EXPOSE 3000
CMD ["npm", "start"]


# Build: -------

#sudo docker build --pull --rm -f "DOCKERFILE" -t 7771512001/frontend_ayd1vacas:latest "./"

# Push: --------


#docker push 7771512001/frontend_ayd1vacas

#docker pull 7771512001/frontend_ayd1vacas