name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Change to 'Back' directory
      run: cd Back
      working-directory: ${{ github.workspace }}
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ github.workspace }}/Back
    # - run: npm run build --if-present
    # - run: npm test
